// Generated by CoffeeScript 1.12.7
var Util;

Util = require('../util');

module.exports = {
  parseLegacyLayerName: function() {
    var len;
    len = Util.pad4(this.file.readByte());
    return this.legacyName = this.file.readString(len);
  }
};
