// Generated by CoffeeScript 1.12.7
module.exports = {
  RAW: require('./image_formats/raw'),
  RLE: require('./image_formats/rle'),
  LayerRLE: require('./image_formats/layer_rle'),
  LayerRAW: require('./image_formats/layer_raw')
};
