// Generated by CoffeeScript 1.12.7
module.exports = {
  toPng: function() {
    return this.layer.image.toPng();
  },
  saveAsPng: function(output) {
    return this.layer.image.saveAsPng(output);
  }
};
